package dk.easv.mrs.DAL.db;

// Project imports
import dk.easv.mrs.BE.Movie;
import dk.easv.mrs.DAL.IMovieDataAccess;
import dk.easv.mrs.util.MRSException;

// Java imports
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class MovieDAO_DB implements IMovieDataAccess {

    private final DBConnector dbConnector = new DBConnector();

    public MovieDAO_DB() throws MRSException {}

    /**
     * CRUD - Get all
     * @return
     * @throws MRSException
     */
    @Override
    public List<Movie> getAllMovies() throws MRSException {

        ArrayList<Movie> allMovies = new ArrayList<>();

        // try-with-resources
        try (Connection conn = dbConnector.getConnection();
             Statement stmt = conn.createStatement())
        {
            String sql = "SELECT * FROM dbo.Movie";
            ResultSet rs = stmt.executeQuery(sql);

            // Loop through rows from the database result set
            while (rs.next()) {

                //Map DB row to Movie object
                int id = rs.getInt("Id");
                String title = rs.getString("Title");
                int year = rs.getInt("year");

                Movie movie = new Movie(id, year, title);
                allMovies.add(movie);
            }
            return allMovies;
        }
        catch (SQLException ex)
        {
            throw new MRSException("Could not get movies from database", ex);
        }
    }


    /**
     * CRUD - create new
     * @param movie
     * @return
     * @throws MRSException
     */
    @Override
    public Movie createMovie(Movie movie) throws MRSException {
        String sql = "INSERT INTO dbo.Movie (Title,Year) VALUES (?,?);";

        // try-with-resources makes sure we close db connection etc.
        try (Connection conn = dbConnector.getConnection()) {
            PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            // Bind parameters
            stmt.setString(1,movie.getTitle());
            stmt.setInt(2, movie.getYear());

            // Run the specified SQL statement
            stmt.executeUpdate();

            // Get the generated ID from the DB
            ResultSet rs = stmt.getGeneratedKeys();
            int id = 0;

            if (rs.next()) {
                id = rs.getInt(1);
            }

            // Create movie object and send up the layers
            // We need the ID generated by the DB in the GUI
            Movie createdMovie = new Movie(id, movie.getYear(), movie.getTitle());

            return createdMovie;
        }
        catch (SQLException ex)
        {
            throw new MRSException("Could not create movie in the database", ex);
        }
    }


    /**
     * CRUD - update existing
     * @param movie
     * @throws MRSException
     */
    @Override
    public void updateMovie(Movie movie) throws MRSException {
        // SQL command
        String sql = "UPDATE dbo.Movie SET Title = ?, Year = ? WHERE ID = ?";

        try (Connection conn = dbConnector.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql))
        {
            // Bind parameters
            stmt.setString(1,movie.getTitle());
            stmt.setInt(2, movie.getYear());
            stmt.setInt(3, movie.getId());

            // Run the specified SQL statement
            stmt.executeUpdate();
        }
        catch (SQLException ex)
        {
            throw new MRSException("Could not update movie in the database.", ex);
        }
    }

    /**
     * CRUD - delete existing
     * @param movie
     * @throws MRSException
     */
    @Override
    public void deleteMovie(Movie movie) throws MRSException {

        // SQL command
        String sql = "DELETE FROM dbo.Movie WHERE ID = ?;";

        try (Connection conn = dbConnector.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql))
        {
            // Bind parameters
            stmt.setInt(1, movie.getId());

            // Run the specified SQL statement
            stmt.executeUpdate();
        }
        catch (SQLException ex)
        {
            throw new MRSException("Error deleting movie in the database.", ex);
        }
    }
}
