package dk.easv.mrs.DAL.db;

// Project imports
import dk.easv.mrs.BE.Movie;
import dk.easv.mrs.BE.Rating;
import dk.easv.mrs.DAL.IRepository;

// Java imports
import java.io.IOException;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;


public class RatingDAO_DB implements IRepository<Rating> {

    private DBConnector dbConnector = new DBConnector();

    public RatingDAO_DB() throws IOException {}

    @Override
    public List<Rating> getAll() throws Exception {

        List<Rating> allObjects = new ArrayList<>();

        // try-with-resources
        try (Connection conn = dbConnector.getConnection();
             Statement stmt = conn.createStatement())
        {
            String sql = "SELECT * FROM dbo.Rating";

            ResultSet rs = stmt.executeQuery(sql);

            // Loop through rows from the database result set
            while (rs.next()) {

                //Map DB row to Movie object
                int ratingId = rs.getInt("ratingId");
                int movieId = rs.getInt("movieId");
                int userId = rs.getInt("userId");
                int score = rs.getInt("score");

                allObjects.add(new Rating(ratingId, movieId, userId, score));
            }
            return allObjects;

        }

        catch (SQLException ex)
        {
            ex.printStackTrace();
            throw new Exception("Could not get movies from database", ex);
        }
    }

    @Override
    public Rating getOne(Rating id) throws Exception {
        return null;
    }

    @Override
    public Rating create(Rating r) throws Exception {
        String sql = "INSERT INTO dbo.Rating (movieId,userId,score) VALUES (?,?,?);";

        // try-with-resources makes sure we close db connection etc.
        try (Connection conn = dbConnector.getConnection()) {
            PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            // Bind parameters
            stmt.setInt(1, r.getMovieId());
            stmt.setInt(2, r.getUserId());
            stmt.setInt(3, r.getScore());

            // Run the specified SQL statement
            stmt.executeUpdate();

            // Get the generated ID from the DB
            ResultSet rs = stmt.getGeneratedKeys();
            int id = 0;

            if (rs.next()) {
                id = rs.getInt(1);
            }

            // Create object and send up the layers
            // We need the ID generated by the DB in the GUI
            return new Rating(id, r.getMovieId(), r.getUserId(), r.getScore());
        }
        catch (SQLException ex)
        {
            ex.printStackTrace();
            throw new Exception("Could not create movie", ex);
        }
    }

    @Override
    public void update(Rating r) throws Exception {
        // SQL command
        String sql = "UPDATE dbo.Rating SET Title = ?, Year = ? WHERE ID = ?";

        try (Connection conn = dbConnector.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql))
        {
            // Bind parameters
            //stmt.setString(1,movie.getTitle());
            //stmt.setInt(2, movie.getYear());
            //stmt.setInt(3, movie.getId());

            // Run the specified SQL statement
            stmt.executeUpdate();
        }
        catch (SQLException ex)
        {
            // fixme: optionally log to file, db etc.
            throw new Exception("Could not get movies from database.", ex);
        }
    }

    @Override
    public void delete(Rating r) throws Exception {

        // SQL command
        String sql = "DELETE FROM dbo.Movie WHERE ID = ?;";

        try (Connection conn = dbConnector.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql))
        {
            // Bind parameters
            //stmt.setInt(1, movie.getId());

            // Run the specified SQL statement
            stmt.executeUpdate();
        }
        catch (SQLException ex)
        {
            // fixme: optionally log to file, db etc.
            throw new Exception("Could not get movies from database.", ex);
        }
    }
}
